### ISSUE TITLE
Coverage output potentially confusing

### ISSUE THREAD

**Issue by chrzyki** [lexibank/phylogenetics-data-management-tutorial#2]
I like the way the coverage is reported with

```python
# Check mutual coverage
for i in range(wl.height, 0, -1):
    if mutual_coverage_check(wl, i):
        print("Minimal mutual coverage is at {0} concept pairs.".format(i))
        break


# check avarage coverage
print('Avarage coverage is {0:.2f}.'.format(average_coverage(wl)))
```

The output

```
Minimal mutual coverage is at 87 concept pairs.
Avarage coverage is 0.94.
```

I think can be potentially confusing since the tutorial text says: "Which, for this dataset, will report a reasonable 87% minimal mutual coverage and 94% average coverage."

**Comment by tresoldi** [comment]
The text is wrong, the coverage is of 87 concept, not 87%. Fixing it.

**Comment by tresoldi** [comment]
I mean, it is 87% because there are 100 concepts, but you are right that it is confusing if we expect people to reuse the code.
